language: cpp

branches:
  only:
    - master-linux
    
notifications:
  recipients:
    - timothy.shields@live.com
  email:
    on_success: never
    on_failure: never
    
compiler:
  - clang
  
script: 
  - cmake -G "Unix Makefiles" -D CMAKE_INSTALL_PREFIX:STRING=./install --build ./build ./src
  - make
